### PR TITLE
Fix: version comparison function

### PR DESCRIPTION
**Pull request by nopeless**
This crashed my build

### CODE REVIEW

**Comment by brianferguson** [comment]
Good catch.

I am curious though. That function is only called in 2 instances. 1 is the comparison between the "new" Rainmeter version versus the currently installed version. The other comparison is between the minimum Windows version (from the status file), and the current Windows OS version.

Do you happen to know which comparison crashed?

-Brian

**Comment by brianferguson** [comment]
Good catch.

I am curious though. That function is only called in 2 instances. 1 is the comparison between the "new" Rainmeter version versus the currently installed version. The other comparison is between the minimum Windows version (from the status file), and the current Windows OS version.

Do you happen to know which comparison crashed?

-Brian

**Comment by nopeless** [comment]
@brianferguson `0.0.0.0` against `4.5.17`

**Comment by brianferguson** [comment]
Ok, I replicated this. Looks like it might only effect new installs, or at least ones that haven't done any update checking.

We will get a new version out right away.

Thanks!
-Brian

**Pull request merged**
